USE BAITHUCHANHSO1_2
GO
CREATE VIEW V1 AS
SELECT * FROM SANPHAM;
GO
SELECT * FROM V1

GO
CREATE VIEW V2 AS
SELECT MASP,TENSP,SOLUONG,MAUSAC,GIABAN,DONVITINH,MOTA
FROM SANPHAM
GO
SELECT * FROM V2 ORDER BY GIABAN DESC


GO
CREATE VIEW V3 AS
SELECT * FROM HANGSX
WHERE TENHANG = N'SAMSUNG'
GO
SELECT * FROM V3


GO
CREATE VIEW V4 AS
SELECT * FROM NHANVIEN
WHERE PHONG = N'KẾ TOÁN' AND GIOITINH = N'NỮ'  
GO
SELECT * FROM V4


GO
CREATE VIEW V5 AS
SELECT N.SOHDN, SP.MASP, SP.TENSP, HANGSX.TENHANG, N.SOLUONGN, N.DONGIAN, N.SOLUONGN * N.DONGIAN AS TIENNHAP, SP.MAUSAC, SP.DONVITINH, N.NGAYNHAP, NV.TENNV, NV.PHONG
FROM BANGNHAP N
JOIN SANPHAM SP ON N.MASP = SP.MASP
JOIN HANGSX ON SP.MAHANGSX = HANGSX.MAHANGSX
JOIN NHANVIEN NV ON N.MANV = NV.MANV

GO
SELECT SOHDN, MASP, TENSP, TENHANG, SOLUONGN, DONGIAN, SOLUONGN * DONGIAN AS TIENNHAP, MAUSAC, DONVITINH, NGAYNHAP, TENNV, PHONG
FROM V5 
ORDER BY SOHDN ASC


GO
CREATE VIEW V6 AS
SELECT X.SOHDX, SP.MASP, SP.TENSP, HANGSX.TENHANG, X.SOLUONGX, SP.GIABAN, X.SOLUONGX * SP.GIABAN AS TIENNHAP, SP.MAUSAC, SP.DONVITINH, X.NGAYXUAT, NV.TENNV, NV.PHONG
FROM BANGXUAT X
JOIN SANPHAM SP ON X.MASP = SP.MASP
JOIN HANGSX ON SP.MAHANGSX = HANGSX.MAHANGSX
JOIN NHANVIEN NV ON X.MANV = NV.MANV
WHERE YEAR(X.NGAYXUAT) = 2018 AND MONTH(X.NGAYXUAT) = 10

GO
SELECT SOHDX, MASP, TENSP,TENHANG, SOLUONGX, GIABAN, SOLUONGX * GIABAN AS TIENNHAP, MAUSAC, DONVITINH, NGAYXUAT, TENNV, PHONG
FROM V6 
ORDER BY SOHDX ASC


GO
CREATE VIEW V7 AS
SELECT N.SOHDN, SP.TENSP, N.SOLUONGN, N.DONGIAN, N.NGAYNHAP, NV.TENNV, NV.PHONG
FROM BANGNHAP N
JOIN SANPHAM SP ON N.MASP = SP.MASP
JOIN HANGSX ON SP.MAHANGSX = HANGSX.MAHANGSX
JOIN NHANVIEN NV ON N.MANV = NV.MANV
WHERE YEAR (N.NGAYNHAP) = 2017 AND TENHANG = N'SAMSUNG'
GO
SELECT * FROM V7


GO
CREATE VIEW V8 AS
SELECT TOP 10 X.SOHDX, SP.MASP, X.MANV, X.NGAYXUAT, X.SOLUONGX, SP.GIABAN
FROM BANGXUAT X
JOIN SANPHAM SP ON X.MASP = SP.MASP
ORDER BY GIABAN DESC
GO
SELECT * FROM V8


GO
CREATE VIEW V9 AS
SELECT TOP 10 * FROM SANPHAM
ORDER BY GIABAN DESC
GO
SELECT * FROM V9


GO
CREATE VIEW V10 AS
SELECT SP.MASP, SP.TENSP, SP.MAUSAC, SP.DONVITINH, SP.GIABAN, HS.TENHANG AS HANGSX_TENHANG
FROM SANPHAM SP
INNER JOIN HANGSX HS ON SP.MAHANGSX = HS.MAHANGSX
WHERE HS.TENHANG = 'SAMSUNG' AND SP.GIABAN BETWEEN 1000000 AND 50000000
GO
SELECT * FROM V10


GO
CREATE VIEW V11 AS
SELECT N.SOHDN, SP.MASP, N.MANV,HX.TENHANG, N.NGAYNHAP, N.SOLUONGN, N.DONGIAN, N.SOLUONGN*N.DONGIAN AS TONGTIEN
FROM BANGNHAP N
JOIN SANPHAM SP ON N.MASP = SP.MASP
JOIN HANGSX HX ON SP.MAHANGSX = HX.MAHANGSX
WHERE YEAR(NGAYNHAP) = 2018
GO
SELECT * FROM V11


GO
CREATE VIEW V12 AS
SELECT  X.SOHDX, SP.MASP, X.MANV, X.NGAYXUAT, X.SOLUONGX, SP.GIABAN, X.SOLUONGX * SP.GIABAN AS TONGTIENXUAT
FROM BANGXUAT X
JOIN SANPHAM SP ON X.MASP = SP.MASP
WHERE YEAR(X.NGAYXUAT) = 2020 AND MONTH(X.NGAYXUAT) = 6 AND DAY(X.NGAYXUAT) = 14
GO
SELECT * FROM V12


GO
CREATE VIEW V13 AS
SELECT TOP 1 N.SOHDN, N.NGAYNHAP
FROM BANGNHAP N
WHERE YEAR(N.NGAYNHAP) = 2018
ORDER BY (N.SOLUONGN * N.DONGIAN) DESC
GO
SELECT * FROM V13


GO
CREATE VIEW V14 AS
SELECT TOP 10 N.MANV, SP.TENSP, N.SOLUONGN
FROM BANGNHAP N
JOIN SANPHAM SP ON N.MASP = SP.MASP
ORDER BY SOLUONGN DESC
GO
SELECT * FROM V14


GO
CREATE VIEW V15 AS
SELECT SP.MASP, SP.TENSP, HX.TENHANG, N.SOLUONGN, N.MANV
FROM SANPHAM SP 
JOIN HANGSX HX ON SP.MAHANGSX = HX.MAHANGSX
JOIN BANGNHAP N ON SP.MASP = N.MASP
WHERE MANV = N'NV01' AND TENHANG = N'SAMSUNG'
GO
SELECT * FROM V15


GO
CREATE VIEW V16 AS
SELECT N.MANV, N.SOHDN, N.MASP, N.SOLUONGN, N.NGAYNHAP
FROM BANGNHAP N
JOIN NHANVIEN NV ON N.MANV = NV.MANV
JOIN BANGXUAT X ON NV.MANV = X.MANV
WHERE X.MASP='SP02' AND N.MANV = 'NV01'
GO
SELECT * FROM V16


GO
CREATE VIEW V17 AS
SELECT N.MANV, TENNV
FROM NHANVIEN N
JOIN BANGXUAT X ON N.MANV=X.MANV
WHERE MASP = 'SP02' AND  YEAR(X.NGAYXUAT) = 2020 AND MONTH(X.NGAYXUAT) = 12 AND DAY(X.NGAYXUAT) = 12
GO
SELECT * FROM V17

